### PR TITLE
MDJ Table

### LINKED ISSUE #16: MDJ Search
- The MDJ table needs to support search for MDJ name, in addition to county.
- When a MDJ is searched, both the MDJ and the county that the MDJ is in should be displayed

### LINKED ISSUE #17: MDJ Table Caret
In Rong's design for the MDJ table, there should be a caret to the left of the County name to indicate that the row can be expanded. This caret should be horizontal when the row is collapsed and vertical when the row is expanded.

If the county has no eligible MDJs, consider excluding a caret.

### LINKED ISSUE #18: MDJ Cash Bail Rate Racial Breakdown
The % of cases MDJs set cash bail for white vs black defendants is simply a placeholder in the MDJ table. Using the data in the JudgeThresholds sheet of the [ACLU Datasheet](https://docs.google.com/spreadsheets/d/1bgQLlNWK1d9tmb6NU1tcY52NwZBU7r7JcBiFjchncV4/edit#gid=1009028934), calculate this number and add this data.

Additionally, calculate the % difference

### LINKED ISSUE #21: Search Outliers
Search does not display outliers if "show outliers" is not enabled. After discussing with Rong, we've decided that, if you search for a outlier, it should appear, whether or not "show outliers" is enabled.

### PR DESCRIPTION
**Pull request by apothuku**
Adds the MDJ table, which breaks down bail distribution and cash bail rates by race for each county and each MDJ within each county.

### CODE REVIEW

**Comment by apothuku** [comment]
I see some strange positioning behavior for the bail type dist visualization:
Screen Shot 2020-10-25 at 9 05 46 PM

Is this some side effect of using display: grid?

**Comment by apothuku** [comment]
Closes #21 #18 #17 #16

**Comment by alexwgraves** [comment]
Can you delete the dist changes here? The easiest way to do that should be to copy the dist folder that's currently in master and replace the dist folder on this branch with that one.

**Review by alexwgraves — APPROVED** [review]

**Comment by alexwgraves** [comment]
Merged into #14

**Pull request closed without merging**
